# Site settings
title: Project Pool
email: alexandreguillet@operamail.com
description: > # this means to ignore newlines until "baseurl:"
 This website  has a meaning. No possible doubt about it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:  Lugburz

# Build settings
markdown: kramdown
